spring:
  application:
    name: smart-bin-server
server:
  port: 8888

app:
  thingsboard:
    url: https://demo.thingsboard.io
    provisioning:
      provision-key: tcwdf3lza9hg2qf04yuv
      provision-secret: c841x8r2a94fatb42jbp
  ai-server:
    url: http://localhost:8081
